# SOPS Configuration
#
# Keys (all work for decrypt, any available used for encrypt):
#   - Transit: OpenBao server-side encryption (primary)
#   - KMS: AWS fallback (via SOPS_KMS_ARN env var)
#   - Age: Offline emergency / bootstrap

creation_rules:
  - path_regex: secrets/.*\.ya?ml$
    hc_vault_transit_uri: https://bao.home.shdr.ch/v1/aether/keys/sops
    age: age132mw5qfj4f90cwgjw0rdtr0qyx7dxrgz78vze6fgm52mcqsrgutqnzxjp5

  - path_regex: ansible/.*vault.*\.ya?ml$
    hc_vault_transit_uri: https://bao.home.shdr.ch/v1/aether/keys/sops
    age: age132mw5qfj4f90cwgjw0rdtr0qyx7dxrgz78vze6fgm52mcqsrgutqnzxjp5

  - path_regex: .*\.enc\..*$
    hc_vault_transit_uri: https://bao.home.shdr.ch/v1/aether/keys/sops
    age: age132mw5qfj4f90cwgjw0rdtr0qyx7dxrgz78vze6fgm52mcqsrgutqnzxjp5
