# yamllint configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '*.yaml.j2'
  - '*.yml.j2'
ignore-from-file:
  - .gitignore
rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values:
      - "true"
      - "false"
      - 'yes'
      - 'no'
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable
  # Allow Jinja2 syntax in templates
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
