version: "3"

# Minimal Taskfile for Nix workflow
# Most tools are just available: tofu, ansible, sops, aws, step, bao
# This file only contains multi-step workflows and playbook shortcuts

vars:
  CACHE_DIR: ${HOME}/.aether-toolbox

env:
  ANSIBLE_CONFIG: ./ansible/ansible.cfg

tasks:
  # ===========================================================================
  # Auth (multi-step flows worth wrapping)
  # ===========================================================================
  login:
    desc: Unified SSO login (AWS + OpenBao + SSH cert)
    cmds:
      - mkdir -p {{.CACHE_DIR}}/bao {{.CACHE_DIR}}/step
      - AETHER_CACHE_DIR={{.CACHE_DIR}} ./scripts/login.sh {{.CLI_ARGS}}

  login:status:
    desc: Check auth status
    cmds:
      - AETHER_CACHE_DIR={{.CACHE_DIR}} ./scripts/login.sh --status

  # ===========================================================================
  # Tofu (only compound operations)
  # ===========================================================================
  tofu:init:
    desc: Init with backend config
    cmds:
      - sh ./scripts/create-tofu-state-config.sh
      - tofu -chdir=tofu init -backend-config=../config/tofu-state.config -upgrade -reconfigure

  tofu:apply:
    desc: Apply + write outputs
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        tofu -chdir=tofu apply {{.CLI_ARGS}}
      - tofu -chdir=tofu output -json > ./secrets/tf-outputs.json

  tofu:plan:
    desc: Plan changes
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        tofu -chdir=tofu plan {{.CLI_ARGS}}

  tofu:refresh:
    desc: Refresh + write outputs
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        tofu -chdir=tofu refresh-only {{.CLI_ARGS}}
      - tofu -chdir=tofu output -json > ./secrets/tf-outputs.json

  # ===========================================================================
  # Secrets (only needs Bao env vars - AWS uses ~/.aws/credentials, age uses .sops.yaml)
  # ===========================================================================
  sv:
    desc: View secrets
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        sops -d ./secrets/secrets.yml

  se:
    desc: Edit secrets
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        sops ./secrets/secrets.yml

  sg:
    desc: "Get secret (usage: task sg -- .path.to.key)"
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        sops -d ./secrets/secrets.yml | yq '{{.CLI_ARGS}}'

  sl:
    desc: List secret keys
    cmds:
      - |
        # [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        sops -d ./secrets/secrets.yml | yq '.. | path | select(length > 0) | "." + join(".")'

  sops:rotate:
    desc: Rotate all secrets with current keys
    cmds:
      - |
        [ -f "{{.CACHE_DIR}}/bao/token" ] && export VAULT_ADDR=https://bao.home.shdr.ch VAULT_TOKEN=$(cat {{.CACHE_DIR}}/bao/token)
        find secrets -name '*.yml' -o -name '*.yaml' | xargs -I{} sops updatekeys --yes {}

  # ===========================================================================
  # Ansible Galaxy (worth automating)
  # ===========================================================================
  galaxy:
    desc: Install Ansible dependencies
    dir: ./ansible
    cmds:
      - ansible-galaxy collection install -r requirements.yml
      - ansible-galaxy role install -r requirements.yml

  # ===========================================================================
  # Playbooks
  # ===========================================================================
  provision:infra:
    cmds: [task: tofu:init, task: tofu:apply]

  ansible:playbook:
    cmds:
      - ansible-playbook ansible/playbooks/{{.CLI_ARGS}}
  provision:router:
    cmds:
      - ansible-playbook ansible/playbooks/home_router/site.yml
  configure:router:
    cmds: [ansible-playbook ansible/playbooks/home_router/configure_router.yml]
  provision:nfs:
    cmds: [ansible-playbook ansible/playbooks/network_file_server/site.yml]
  configure:gateway:
    cmds: [ansible-playbook ansible/playbooks/home_gateway_stack/site.yml]
  configure:caddy:
    cmds: [ansible-playbook ansible/playbooks/home_gateway_stack/caddy/site.yml]
  configure:monitoring:
    cmds: [ansible-playbook ansible/playbooks/monitoring_stack/site.yml]
  configure:dokploy:
    cmds: [ansible-playbook ansible/playbooks/dokploy/site.yml]
  configure:gitlab:
    cmds: [ansible-playbook ansible/playbooks/gitlab/site.yml]
  configure:backup:
    cmds: [ansible-playbook ansible/playbooks/backup_stack/site.yml]
  configure:iot:
    cmds: [ansible-playbook ansible/playbooks/iot_management_stack/site.yml]
  configure:vm-agents:
    cmds: [ansible-playbook ansible/playbooks/setup_vm_monitoring_agents.yml]
  configure:host-agents:
    cmds: [ansible-playbook ansible/playbooks/setup_host_monitoring_agents.yml]
  configure:cockpit-agents:
    cmds: [ansible-playbook ansible/playbooks/setup_cockpit_agents.yml]
  configure:dev-workstation:
    cmds: [ansible-playbook ansible/playbooks/dev_workstation/site.yml]
  configure:cockpit:
    cmds: [ansible-playbook ansible/playbooks/cockpit/site.yml]
  configure:gpu-workstation:
    cmds: [ansible-playbook ansible/playbooks/gpu_workstation/site.yml]
  configure:ai-tools:
    cmds: [ansible-playbook ansible/playbooks/ai_tool_stack/site.yml]
  configure:media-stack:
    cmds: [ansible-playbook ansible/playbooks/media_stack/site.yml]
  configure:messaging-stack:
    cmds: [ansible-playbook ansible/playbooks/messaging_stack/site.yml]
  configure:ups-management-stack:
    cmds: [ansible-playbook ansible/playbooks/ups_management_stack/site.yml]
  configure:dokku:
    cmds: [ansible-playbook ansible/playbooks/dokku/site.yml]
  configure:smallweb:
    cmds: [ansible-playbook ansible/playbooks/smallweb/site.yml]
  provision:keycloak:
    cmds: [ansible-playbook ansible/playbooks/keycloak/site.yml]
  configure:keycloak:
    cmds: [ansible-playbook ansible/playbooks/keycloak/deploy_keycloak.yml]
  configure:public-gateway:
    cmds: [ansible-playbook ansible/playbooks/public_gateway_stack/site.yml]
  provision:game-server:
    cmds: [ansible-playbook ansible/playbooks/game_server/site.yml]
  provision:step-ca:
    cmds: [ansible-playbook ansible/playbooks/step_ca/site.yml]
  provision:step-ca-trust:
    cmds: [ansible-playbook ansible/playbooks/step_ca/provision_aws_trust.yml]
  configure:step-ca:
    cmds: [ansible-playbook ansible/playbooks/step_ca/deploy_step_ca.yml]
  provision:openbao:
    cmds: [ansible-playbook ansible/playbooks/openbao/site.yml]
  provision:openbao-kms:
    cmds: [ansible-playbook ansible/playbooks/openbao/provision_aws_kms.yml]
  configure:openbao:
    cmds: [ansible-playbook ansible/playbooks/openbao/deploy_openbao.yml]
  configure:ssh-ca:
    cmds: [ansible-playbook ansible/playbooks/configure_ssh_ca_trust.yml]
  configure:ssh-keys:
    cmds: [ansible-playbook ansible/playbooks/update_authorized_keys.yml]
  baseline:machines:
    cmds: [ansible-playbook ansible/playbooks/baseline_machines.yml]
  baseline:vms:
    cmds: [ansible-playbook ansible/playbooks/baseline_vms.yml]

  configure:all:
    cmds:
      - task: configure:gateway
      - task: configure:monitoring
      - task: configure:dokploy
      - task: configure:gitlab
      - task: configure:backup
