FROM ghcr.io/ublue-os/bazzite-deck:stable

RUN rpm-ostree install cloud-init && \
    systemctl enable cloud-init cloud-init-local cloud-final cloud-config && \
    ostree container commit

RUN echo "datasource_list: [ NoCloud, ConfigDrive ]" > /etc/cloud/cloud.cfg.d/90_proxmox.cfg
