---
site_wireguard_interface: wg-cloud
site_wireguard_mtu: 1380
site_wireguard_listen_port: null
site_wireguard_addresses: []
site_wireguard_peers: []
site_wireguard_source_address: null
site_wireguard_remote_prefixes: []
site_wireguard_policy_rules: []
site_wireguard_enable_forwarding: false
site_wireguard_firewall_profile: spoke
