---
- name: reload certificate monitoring systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
  tags: [monitoring-agent]

- name: restart x509 certificate exporter
  ansible.builtin.systemd:
    name: aether-x509-certificate-exporter.service
    state: restarted
  become: true
  tags: [monitoring-agent]

- name: restart systemd exporter
  ansible.builtin.systemd:
    name: aether-systemd-exporter.service
    state: restarted
  become: true
  tags: [monitoring-agent]
