# Wazuh Stack - Host-based IDS
# - Manager: Agents connect to port 1514, API on 55000
# - Indexer: OpenSearch for state storage (port 9200)
# - Dashboard: Web UI (port 5601)
#
# Certificates: Generated by wazuh-certs-generator container (official approach)
# See: https://github.com/wazuh/wazuh-docker/blob/master/single-node/generate-indexer-certs.yml
{ config, lib, pkgs, ... }:

{
  # OpenBao templates for Wazuh secrets
  aether.openbao-agent.templates = {
    # Plain passwords for security-init hashing
    "wazuh-indexer-password" = {
      contents = ''{{ with secret "kv/data/aether/wazuh" }}{{ .Data.data.indexer_password }}{{ end }}'';
      perms = "0600";
    };
    "wazuh-dashboard-password" = {
      contents = ''{{ with secret "kv/data/aether/wazuh" }}{{ .Data.data.dashboard_password }}{{ end }}'';
      perms = "0600";
    };
    # Env file for wazuh-manager container
    "wazuh-manager.env" = {
      contents = ''
{{ with secret "kv/data/aether/wazuh" }}INDEXER_URL=https://wazuh.indexer:9200
INDEXER_USERNAME=admin
INDEXER_PASSWORD={{ .Data.data.indexer_password }}
FILEBEAT_SSL_VERIFICATION_MODE=full
SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
SSL_CERTIFICATE=/etc/ssl/filebeat.pem
SSL_KEY=/etc/ssl/filebeat.key
API_USERNAME=wazuh-wui
API_PASSWORD={{ .Data.data.api_password }}{{ end }}
'';
      perms = "0600";
      restartServices = [ "wazuh.service" ];
    };
    # Env file for wazuh-dashboard container
    "wazuh-dashboard.env" = {
      contents = ''
{{ with secret "kv/data/aether/wazuh" }}INDEXER_USERNAME=admin
INDEXER_PASSWORD={{ .Data.data.indexer_password }}
WAZUH_API_URL=https://wazuh.manager
DASHBOARD_USERNAME=kibanaserver
DASHBOARD_PASSWORD={{ .Data.data.dashboard_password }}
API_USERNAME=wazuh-wui
API_PASSWORD={{ .Data.data.api_password }}{{ end }}
'';
      perms = "0600";
      restartServices = [ "wazuh-dashboard.service" ];
    };
    # Wazuh Dashboard API config with credentials
    "wazuh.yml" = {
      contents = ''
{{ with secret "kv/data/aether/wazuh" }}hosts:
  - 1513629884013:
      url: "https://wazuh.manager"
      port: 55000
      username: wazuh-wui
      password: "{{ .Data.data.api_password }}"
      run_as: false{{ end }}
'';
      perms = "0644";
      restartServices = [ "wazuh-dashboard.service" ];
    };
  };

  # Wazuh alerts JSON logs (sent to Loki via OTEL)
  aether.otel-agent.jsonFilelogs.wazuh = {
    include = [ "/var/lib/wazuh/logs/alerts/alerts.json" ];
    timestampField = "timestamp";
    resourceAttributes."log.source" = "wazuh";
  };
  # Data directories for Wazuh stack
  systemd.tmpfiles.rules = [
    # Wazuh certificates directory (generated by wazuh-certs-generator)
    "d /var/lib/wazuh-certs 0755 root root -"
    # Wazuh data directories (matches official docker-compose volumes)
    # UID 999 = wazuh user inside container
    # o+x on logs dirs so OTEL can traverse and read alerts
    "d /var/lib/wazuh 0755 root root -"
    "d /var/lib/wazuh/logs 0775 999 999 -"
    "d /var/lib/wazuh/logs/alerts 0775 999 999 -"
    "d /var/lib/wazuh/logs/archives 0770 999 999 -"
    "d /var/lib/wazuh/logs/firewall 0770 999 999 -"
    "d /var/lib/wazuh/etc 0770 999 999 -"
    "d /var/lib/wazuh/queue 0770 999 999 -"
    "d /var/lib/wazuh/var 0755 root root -"
    "d /var/lib/wazuh/var/run 0755 root root -"
    "d /var/lib/wazuh/var/multigroups 0770 999 999 -"
    "d /var/lib/wazuh/api-config 0770 999 999 -"
    "d /var/lib/wazuh/active-response 0755 root root -"
    "d /var/lib/wazuh/wodles 0755 root root -"
    # Wazuh Indexer (OpenSearch) - UID 1000 inside container
    "d /var/lib/wazuh-indexer 0770 1000 1000 -"
    # Wazuh Dashboard - UID 1000 inside container
    "d /var/lib/wazuh-dashboard 0755 root root -"
    "d /var/lib/wazuh-dashboard/config 0755 1000 1000 -"
  ];

  # Wazuh certificate generator config (matches official docker certs.yml)
  # See: https://github.com/wazuh/wazuh-docker/blob/master/single-node/config/certs.yml
  environment.etc."wazuh-certs/certs.yml".text = builtins.readFile ./config/certs.yml;

  # OpenSearch config for Wazuh Indexer (from official single-node/config/wazuh_indexer/wazuh.indexer.yml)
  environment.etc."wazuh-indexer/opensearch.yml".text = builtins.readFile ./config/opensearch.yml;

  # Wazuh Dashboard OpenSearch config (from official single-node example)
  environment.etc."wazuh-dashboard/opensearch_dashboards.yml".text = builtins.readFile ./config/opensearch_dashboards.yml;

  # Create podman network for Wazuh stack communication
  systemd.services.wazuh-network = {
    description = "Create Wazuh podman network";
    after = [ "network.target" "podman.service" ];
    wants = [ "podman.service" ];
    wantedBy = [ "multi-user.target" ];
    before = [ "wazuh-indexer.service" "wazuh.service" "wazuh-dashboard.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = "${pkgs.podman}/bin/podman network create wazuh --ignore";
      ExecStop = "${pkgs.podman}/bin/podman network rm wazuh --ignore";
    };
  };

  # Generate Wazuh TLS certificates using official wazuh-certs-generator
  systemd.services.wazuh-certs-generate = {
    description = "Generate Wazuh TLS certificates";
    after = [ "network.target" "wazuh-network.service" ];
    requires = [ "wazuh-network.service" ];
    wantedBy = [ "multi-user.target" ];
    before = [ "wazuh-indexer.service" "wazuh.service" "wazuh-dashboard.service" ];
    path = [ pkgs.podman ];
    unitConfig = {
      # Only run if certs don't exist yet
      ConditionPathExists = "!/var/lib/wazuh-certs/root-ca.pem";
    };
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "generate-wazuh-certs" (builtins.readFile ./scripts/generate-certs.sh);
    };
  };

  # Initialize OpenSearch Security plugin (runs securityadmin)
  # This creates the .opendistro_security index with custom passwords from OpenBao
  systemd.services.wazuh-security-init = {
    description = "Initialize Wazuh Indexer Security";
    after = [ "wazuh-indexer.service" "vault-agent.service" ];
    requires = [ "wazuh-indexer.service" ];
    wants = [ "vault-agent.service" ];
    wantedBy = [ "multi-user.target" ];
    before = [ "wazuh.service" "wazuh-dashboard.service" ];
    path = [ pkgs.podman pkgs.curl ];
    unitConfig = {
      # Only run if security index hasn't been initialized
      ConditionPathExists = "!/var/lib/wazuh-indexer/.security_initialized";
    };
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "init-wazuh-security" (builtins.readFile ./scripts/init-security.sh);
    };
  };

  # Wazuh Indexer (OpenSearch) - stores alerts, vulnerabilities, compliance state
  # Using official config and certificate paths from docker-compose
  virtualisation.quadlet.containers.wazuh-indexer = {
    autoStart = true;
    containerConfig = {
      image = "docker.io/wazuh/wazuh-indexer:4.14.1";
      volumes = [
        "/var/lib/wazuh-indexer:/var/lib/wazuh-indexer:Z"
        # OpenSearch config (from official single-node example)
        "/etc/wazuh-indexer/opensearch.yml:/usr/share/wazuh-indexer/config/opensearch.yml:ro,Z"
        # TLS certificates (paths match opensearch.yml config)
        "/var/lib/wazuh-certs/root-ca.pem:/usr/share/wazuh-indexer/config/certs/root-ca.pem:ro,Z"
        "/var/lib/wazuh-certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem:ro,Z"
        "/var/lib/wazuh-certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.key:ro,Z"
        "/var/lib/wazuh-certs/admin.pem:/usr/share/wazuh-indexer/config/certs/admin.pem:ro,Z"
        "/var/lib/wazuh-certs/admin-key.pem:/usr/share/wazuh-indexer/config/certs/admin-key.pem:ro,Z"
      ];
      publishPorts = [
        "9200:9200/tcp"
      ];
      podmanArgs = [
        "--network=wazuh"
        "--hostname=wazuh.indexer"
        "--env=OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        "--ulimit=memlock=-1:-1"
        "--ulimit=nofile=65536:65536"
      ];
    };
    serviceConfig = {
      Restart = "always";
      RestartSec = "10";
    };
    unitConfig = {
      Description = "Wazuh Indexer (OpenSearch)";
      After = [ "wazuh-certs-generate.service" "wazuh-network.service" ];
      Requires = [ "wazuh-certs-generate.service" "wazuh-network.service" ];
    };
  };

  # Wazuh Manager - Host-based IDS manager
  # Using official certificate paths from docker-compose
  virtualisation.quadlet.containers.wazuh = {
    autoStart = true;
    containerConfig = {
      image = "docker.io/wazuh/wazuh-manager:4.14.1";
      volumes = [
        "/var/lib/wazuh/api-config:/var/ossec/api/configuration:Z"
        "/var/lib/wazuh/etc:/var/ossec/etc:Z"
        "/var/lib/wazuh/logs:/var/ossec/logs:Z"
        "/var/lib/wazuh/queue:/var/ossec/queue:Z"
        "/var/lib/wazuh/var/multigroups:/var/ossec/var/multigroups:Z"
        "/var/lib/wazuh/active-response:/var/ossec/active-response/bin:Z"
        "/var/lib/wazuh/wodles:/var/ossec/wodles:Z"
        # TLS certificates for Filebeat (paths match official docker-compose /etc/ssl/)
        "/var/lib/wazuh-certs/root-ca-manager.pem:/etc/ssl/root-ca.pem:ro,Z"
        "/var/lib/wazuh-certs/wazuh.manager.pem:/etc/ssl/filebeat.pem:ro,Z"
        "/var/lib/wazuh-certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key:ro,Z"
      ];
      publishPorts = [
        "1514:1514/tcp"
        "1514:1514/udp"
        "1515:1515/tcp"
        "55000:55000/tcp"
      ];
      podmanArgs = [
        "--network=wazuh"
        "--hostname=wazuh.manager"
        # Environment from OpenBao secrets
        "--env-file=/run/secrets/wazuh-manager.env"
        "--ulimit=memlock=-1:-1"
        "--ulimit=nofile=655360:655360"
      ];
    };
    serviceConfig = {
      Restart = "always";
      RestartSec = "10";
    };
    unitConfig = {
      Description = "Wazuh Manager - Host-based IDS";
      After = [ "wazuh-indexer.service" "wazuh-certs-generate.service" "wazuh-security-init.service" "vault-agent.service" ];
      Requires = [ "wazuh-indexer.service" "wazuh-certs-generate.service" "wazuh-security-init.service" ];
      Wants = [ "vault-agent.service" ];
    };
  };

  # Wazuh Dashboard - Web UI for security analytics
  # Using official certificate paths from docker-compose
  virtualisation.quadlet.containers.wazuh-dashboard = {
    autoStart = true;
    containerConfig = {
      image = "docker.io/wazuh/wazuh-dashboard:4.14.1";
      volumes = [
        # Config files
        "/etc/wazuh-dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:ro,Z"
        "/run/secrets/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml:ro,Z"
        # TLS certificates (paths match opensearch_dashboards.yml)
        "/var/lib/wazuh-certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem:ro,Z"
        "/var/lib/wazuh-certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem:ro,Z"
        "/var/lib/wazuh-certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem:ro,Z"
        # Persistent data
        "/var/lib/wazuh-dashboard/config:/usr/share/wazuh-dashboard/data/wazuh/config:Z"
      ];
      publishPorts = [
        "5601:5601/tcp"
      ];
      podmanArgs = [
        "--network=wazuh"
        "--hostname=wazuh.dashboard"
        # Environment from OpenBao secrets
        "--env-file=/run/secrets/wazuh-dashboard.env"
      ];
    };
    serviceConfig = {
      Restart = "always";
      RestartSec = "10";
    };
    unitConfig = {
      Description = "Wazuh Dashboard - Security Analytics UI";
      After = [ "wazuh-indexer.service" "wazuh.service" "wazuh-certs-generate.service" "wazuh-security-init.service" "vault-agent.service" ];
      Requires = [ "wazuh-indexer.service" "wazuh-certs-generate.service" "wazuh-security-init.service" ];
      Wants = [ "vault-agent.service" ];
    };
  };
}

